spring:
  application:
    name: mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: webflux-mcp-server
        version: 1.0.0

logging:
  level:
    org:
      springframework:
        ai:
          mcp: TRACE

server:
  port: 8099

service:
  store:
    url: http://localhost:8082
