spring:
  application:
    name: mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: webflux-mcp-server
        version: 1.0.0

logging:
  level:
    org:
      springframework:
        ai:
          mcp: TRACE

STORE_SVC_URI:
  http://localhost:8082
ORDER_SVC_URI:
  http://localhost:8084

server:
  port: 8099
