spring:
  application:
    name: mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: webflux-mcp-server
        version: 0.0.1
#        sse-endpoint: /sse
#        sse-message-endpoint: /mcp/messages
#        capabilities:
#          tool: true
#          resource: true
#          prompt: true
#          completion: true
logging:
  level:
    org:
      springframework:
        ai:
          mcp: TRACE

server:
  port: 8099