spring:
  application:
    name: mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: webflux-mcp-server
        version: 1.0.0
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI:http://localhost:8083/oauth/jwks}



jwt:
  audience:  ${AUTH_INTERNAL_AUDIENCE:internal-services}
logging:
  level:
    org:
      springframework:
        ai:
          mcp: TRACE

service:
  store:
    url: http://localhost:8082
  item:
    url: http://localhost:8084

server:
  port: 8099
